name = "MatrixNormTest"
uuid = "946e395a-a902-11e9-38c2-c3243e8e5be8"
authors = ["Nik Počuča"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
